"""Test environment setup and cleanup for tracepatch.

Manages the lifecycle of the ``tph run`` / ``tph clean`` workflow:
creating test runners, saving/loading state, and restoring the
working directory on cleanup.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from tracepatch._cli_output import err, info, ok, warn
from tracepatch._codegen import create_test_runner
from tracepatch._git import check_git_status
from tracepatch._introspect import get_function_signature
from tracepatch._trace import _CACHE_DIR_NAME

if TYPE_CHECKING:
    from tracepatch.config import TracepatchConfig


class SetupState:
    """Tracks what was done during setup for later cleanup."""

    def __init__(self) -> None:
        self.created_files: list[Path] = []
        self.modified_files: list[tuple[Path, str]] = []  # (path, backup_content)
        self.test_runner_path: Path | None = None
        self.cache_dir: Path | None = None

    def save(self, cache_dir: Path) -> None:
        """Save setup state to a JSON file in the cache directory."""
        state_file = cache_dir / "setup_state.json"
        data = {
            "created_files": [str(p) for p in self.created_files],
            "modified_files": [(str(p), content) for p, content in self.modified_files],
            "test_runner_path": str(self.test_runner_path) if self.test_runner_path else None,
            "cache_dir": str(cache_dir),
        }
        with open(state_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        self.cache_dir = cache_dir

    @classmethod
    def load(cls, cache_dir: Path) -> SetupState | None:
        """Load setup state from a JSON file in the cache directory."""
        state_file = cache_dir / "setup_state.json"
        if not state_file.exists():
            return None

        with open(state_file, encoding="utf-8") as f:
            data = json.load(f)

        state = cls()
        state.created_files = [Path(p) for p in data.get("created_files", [])]
        state.modified_files = [(Path(p), content) for p, content in data.get("modified_files", [])]
        test_runner = data.get("test_runner_path")
        state.test_runner_path = Path(test_runner) if test_runner else None
        cache_dir_str = data.get("cache_dir")
        state.cache_dir = Path(cache_dir_str) if cache_dir_str else cache_dir
        return state


def ensure_init_file(directory: Path, state: SetupState) -> None:
    """Ensure ``__init__.py`` exists in *directory*."""
    init_file = directory / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Auto-generated by tracepatch\n", encoding="utf-8")
        state.created_files.append(init_file)


def setup_test_environment(config: TracepatchConfig, working_dir: Path) -> SetupState:
    """Set up test environment based on configuration.

    Parameters
    ----------
    config:
        Loaded TracepatchConfig.
    working_dir:
        Directory to set up in.

    Returns
    -------
    SetupState
        Object describing what was created / modified.
    """
    state = SetupState()

    print("Setting up tracepatch test environment...")
    print()

    # Check Git status
    has_git, staged, unstaged = check_git_status(working_dir)
    if has_git:
        if staged:
            warn("You have staged Git changes:")
            for file in staged[:5]:
                info(f"- {file}")
            if len(staged) > 5:
                info(f"... and {len(staged) - 5} more")
            print()
            info("tracepatch will create files that may affect your Git state.")
            response = input("   Continue? [y/N]: ").strip().lower()
            if response not in ("y", "yes"):
                print("\nSetup cancelled.")
                return state
            print()
        elif unstaged:
            info("Note: You have unstaged Git changes.")
            info("tracepatch will create temporary files in your working directory.")
            print()

    # Check if custom test script is enabled
    if config.test.custom.enabled and config.test.custom.script:
        print("\nUsing custom test script from configuration...")
        runner_dir = working_dir / _CACHE_DIR_NAME
        runner_dir.mkdir(exist_ok=True)
        test_file = runner_dir / "trace_runner.py"
        with open(test_file, "w", encoding="utf-8") as f:
            f.write(config.test.custom.script)

        state.test_runner_path = test_file
        state.created_files.append(test_file)
        ok(f"Created {test_file.relative_to(working_dir)} from custom script")

        cache_dir = runner_dir
        state.save(cache_dir)

        print(f"\n{'=' * 70}")
        print("Setup complete!")
        print(f"{'=' * 70}")
        print()
        warn("IMPORTANT: Do not delete the .tracepatch folder!")
        info("It contains setup state needed for cleanup with 'tph clean'")
        print()
        print("Run tests with:")
        info(f"python {test_file.relative_to(working_dir)}")
        print()
        print("Cleanup with:")
        info("tph clean")
        print()

        return state

    # Auto-generated test runner
    ensure_init_file(working_dir, state)
    if state.created_files and state.created_files[-1].name == "__init__.py":
        ok(f"Created {working_dir / '__init__.py'}")

    # Validate configured files exist
    print("\nValidating test configuration...")
    for file_config in config.test.files:
        file_path = working_dir / file_config.path
        if not file_path.exists():
            err(f"File not found: {file_path}")
        else:
            ok(f"Found {file_path}")
            for func in file_config.functions:
                sig = get_function_signature(file_path, func)
                if sig is not None:
                    params = [p[0] for p in sig if p[0] != "self"]
                    info(f"└─ {func}({', '.join(params)})")
                else:
                    info(f"└─ {func}()")

    # Create test runner
    print("\nCreating test runner...")
    test_runner = create_test_runner(config, working_dir, state)
    ok(f"Created {test_runner.relative_to(working_dir)}")

    # Save state
    cache_dir = working_dir / _CACHE_DIR_NAME
    cache_dir.mkdir(exist_ok=True)
    state.save(cache_dir)

    print(f"\n{'=' * 70}")
    print("Setup complete!")
    print(f"{'=' * 70}")
    print()
    warn("IMPORTANT: Do not delete the .tracepatch folder!")
    info("It contains setup state needed for cleanup with 'tph clean'")
    print()
    print("Run tests with:")
    info(f"python {test_runner.relative_to(working_dir)}")
    print()
    print("Cleanup with:")
    info("tph clean")
    print()

    return state


def cleanup_test_environment(working_dir: Path) -> bool:
    """Clean up test environment using saved state.

    Parameters
    ----------
    working_dir:
        Directory where ``tph run`` was previously executed.

    Returns
    -------
    bool
        ``True`` if cleanup was successful, ``False`` otherwise.
    """
    cache_dir = working_dir / _CACHE_DIR_NAME

    if not cache_dir.exists():
        err("Cache directory not found!")
        info("Cannot cleanup without setup state.")
        return False

    state = SetupState.load(cache_dir)

    if state is None:
        info("No active tracepatch setup found.")
        info("Nothing to clean up.")
        return False

    print("Cleaning up tracepatch test environment...")
    print()

    has_git, staged, unstaged = check_git_status(working_dir)
    if has_git:
        if staged:
            warn("You have staged Git changes:")
            for file in staged[:5]:
                info(f"- {file}")
            if len(staged) > 5:
                info(f"... and {len(staged) - 5} more")
            print()
            info("tracepatch will remove generated files that may affect your Git state.")
            response = input("   Continue? [y/N]: ").strip().lower()
            if response not in ("y", "yes"):
                print("\nCleanup cancelled.")
                return False
            print()
        elif unstaged:
            info("Note: You have unstaged Git changes.")
            info("tracepatch will remove temporary files from your working directory.")
            print()

    # Restore modified files
    for file_path, backup_content in state.modified_files:
        if file_path.exists():
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(backup_content)
            ok(f"Restored {file_path}")

    # Remove created files (except those in cache)
    for file_path in state.created_files:
        if file_path.exists() and not str(file_path).startswith(str(cache_dir)):
            file_path.unlink()
            ok(f"Removed {file_path}")

    # Remove setup state from cache
    state_file = cache_dir / "setup_state.json"
    if state_file.exists():
        state_file.unlink()
        ok("Removed setup state")

    print(f"\n{'=' * 70}")
    print("Cleanup complete!")
    print(f"{'=' * 70}")
    print()
    info("The .tracepatch folder and trace logs have been preserved.")
    print()

    return True
