"""Internal implementation of the tracepatch tracing engine."""

from __future__ import annotations

import datetime
import json
import os
import sys
import threading
import time
from contextvars import ContextVar
from dataclasses import dataclass, field
from pathlib import Path
from types import FrameType
from typing import Any, Optional, TextIO, Union


# ---------------------------------------------------------------------------
# Cache directory management
# ---------------------------------------------------------------------------

_CACHE_DIR_NAME = ".tracepatch_cache"
_CACHE_GITIGNORE = "# Auto-generated by tracepatch. Do not edit.\n*\n"
_CACHE_README = """This directory is managed by tracepatch.

Each .json file is a trace log produced by a trace() context manager.
Files are named with a timestamp and optional label for easy identification.

You can read these logs with:

    from tracepatch import trace
    for entry in trace.logs():
        print(entry["file"], "-", entry["call_count"], "calls")

Or open any file directly -- they are plain JSON.

This directory is git-ignored by default.
"""


def _ensure_cache_dir(base: Union[str, Path, None] = None) -> Path:
    """Create the .tracepatch_cache directory if needed.

    Writes a .gitignore (containing ``*``) and a short README into the
    directory on first creation so the purpose is self-documenting.

    Parameters
    ----------
    base:
        Parent directory for the cache folder, or the cache directory itself.
        Defaults to the current working directory.

    Returns
    -------
    Path to the cache directory.
    """
    if base is None:
        parent = Path.cwd()
        cache_dir = parent / _CACHE_DIR_NAME
    else:
        base_path = Path(base)
        # Check if base is already a cache directory
        if base_path.name == _CACHE_DIR_NAME:
            cache_dir = base_path
        else:
            cache_dir = base_path / _CACHE_DIR_NAME
    
    cache_dir.mkdir(exist_ok=True)

    gitignore = cache_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_CACHE_GITIGNORE, encoding="utf-8")

    readme = cache_dir / "README"
    if not readme.exists():
        readme.write_text(_CACHE_README, encoding="utf-8")

    return cache_dir


# ---------------------------------------------------------------------------
# Trace node: one captured call
# ---------------------------------------------------------------------------

@dataclass
class TraceNode:
    """A single captured function call, forming a tree via children."""

    name: str
    module: str
    args: str
    return_value: Optional[str] = None
    exception: Optional[str] = None
    start: float = 0.0
    end: float = 0.0
    elapsed: float = 0.0
    children: list["TraceNode"] = field(default_factory=list)
    depth: int = 0

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Return a plain dict suitable for JSON serialisation."""
        d: dict[str, Any] = {
            "name": self.name,
            "module": self.module,
            "args": self.args,
            "return_value": self.return_value,
            "start": self.start,
            "end": self.end,
            "elapsed_ms": round(self.elapsed * 1000, 4),
        }
        if self.exception is not None:
            d["exception"] = self.exception
        if self.children:
            d["children"] = [c.to_dict() for c in self.children]
        return d


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_DEFAULT_MAX_REPR = 120
_DEFAULT_MAX_DEPTH = 30
_DEFAULT_MAX_CALLS = 10_000
_DEFAULT_MAX_TIME = 60.0  # seconds


@dataclass(frozen=True)
class TraceConfig:
    """Immutable configuration for a single trace session."""

    ignore_modules: tuple[str, ...] = ()
    max_depth: int = _DEFAULT_MAX_DEPTH
    max_calls: int = _DEFAULT_MAX_CALLS
    max_repr: int = _DEFAULT_MAX_REPR
    max_time: float = _DEFAULT_MAX_TIME  # Maximum trace duration in seconds


# ---------------------------------------------------------------------------
# ASCII tree renderer
# ---------------------------------------------------------------------------

def _format_elapsed(seconds: float) -> str:
    """Human-friendly elapsed time string."""
    ms = seconds * 1000
    if ms < 1:
        return f"{seconds * 1_000_000:.0f}us"
    if ms < 1000:
        return f"{ms:.2f}ms"
    return f"{seconds:.3f}s"


def render_tree(roots: list[TraceNode]) -> str:
    """Render a list of root TraceNodes as a readable ASCII call tree."""
    lines: list[str] = []

    def _walk(node: TraceNode, prefix: str, is_last: bool) -> None:
        connector = "└── " if is_last else "├── "
        ret = ""
        if node.exception is not None:
            ret = f" !! {node.exception}"
        elif node.return_value is not None:
            ret = f" -> {node.return_value}"

        timing = _format_elapsed(node.elapsed)
        label = f"{node.module}.{node.name}({node.args}){ret}  [{timing}]"
        lines.append(f"{prefix}{connector}{label}")

        extension = "    " if is_last else "│   "
        child_prefix = prefix + extension
        for i, child in enumerate(node.children):
            _walk(child, child_prefix, i == len(node.children) - 1)

    for i, root in enumerate(roots):
        _walk(root, "", i == len(roots) - 1)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Context-local trace collector (isolates async tasks)
# ---------------------------------------------------------------------------

_active_collector: ContextVar[Optional["_Collector"]] = ContextVar(
    "tracepatch_active_collector", default=None,
)


class _Collector:
    """Accumulates trace nodes for one execution context.

    Thread-safety: each collector is accessed only from its own context.
    The profile callback checks the ContextVar, so different async tasks
    get different collectors even when sharing an event loop thread.
    """

    def __init__(self, config: TraceConfig, trace_id: str) -> None:
        self.config = config
        self.roots: list[TraceNode] = []
        self.call_count: int = 0
        self.disabled: bool = False
        self.trace_id = trace_id  # Unique ID for correlation in multi-threaded scenarios
        self.start_time = time.perf_counter()  # For max_time enforcement

        # Stack of (node, depth) tracking the open call frames.
        self._stack: list[TraceNode] = []
        # Track seen objects to detect circular references
        self._seen_objects: set[int] = set()
        # Track objects that have already warned about repr failures
        self._warned_objects: set[int] = set()

    # ------------------------------------------------------------------
    # safe repr
    # ------------------------------------------------------------------

    def _safe_repr(self, obj: object) -> str:
        """Safely create a string representation, handling errors and circular refs."""
        limit = self.config.max_repr
        try:
            # Detect circular references
            obj_id = id(obj)
            if obj_id in self._seen_objects:
                return "<circular reference>"
            
            # Track this object temporarily
            self._seen_objects.add(obj_id)
            
            try:
                r = repr(obj)
            except Exception as e:
                # Only log the error once per unique object to avoid noise
                if obj_id not in self._warned_objects:
                    self._warned_objects.add(obj_id)
                    try:
                        import sys
                        print(f"[tracepatch] repr failed: {type(e).__name__}", file=sys.stderr)
                    except Exception:
                        pass
                return "<unprintable>"
            finally:
                # Always clean up
                self._seen_objects.discard(obj_id)
            
            if len(r) > limit:
                return r[: limit - 3] + "..."
            return r
        except Exception:
            # Catch-all: never let repr issues crash the traced code
            return "<error>"

    # ------------------------------------------------------------------
    # Trace callback events
    # ------------------------------------------------------------------

    def _should_ignore(self, frame: FrameType) -> bool:
        """Return True if this frame should be skipped."""
        module = frame.f_globals.get("__name__", "") or ""
        if module.startswith("tracepatch") or module == "threading":
            return True
        for prefix in self.config.ignore_modules:
            if module.startswith(prefix):
                return True
        return False

    def handle_call(self, frame: FrameType) -> bool:
        """Process a call event.  Returns True if the call was recorded."""
        if self.disabled:
            return False

        # Enforce max_time
        if time.perf_counter() - self.start_time > self.config.max_time:
            self.disabled = True
            return False

        if self._should_ignore(frame):
            return False

        code = frame.f_code
        module = frame.f_globals.get("__name__", "") or ""
        depth = len(self._stack)

        # Enforce max_depth.
        if depth >= self.config.max_depth:
            return False

        # Enforce max_calls.
        self.call_count += 1
        if self.call_count > self.config.max_calls:
            self.disabled = True
            return False

        # Capture arguments via frame locals.
        # f_locals is a snapshot; we only capture it at call time.
        args_dict = frame.f_locals.copy()
        args_parts: list[str] = []
        for param, val in args_dict.items():
            args_parts.append(f"{param}={self._safe_repr(val)}")
        args_str = ", ".join(args_parts)
        if len(args_str) > self.config.max_repr:
            args_str = args_str[: self.config.max_repr - 3] + "..."

        node = TraceNode(
            name=code.co_name,
            module=module,
            args=args_str,
            start=time.perf_counter(),
            depth=depth,
        )

        if self._stack:
            self._stack[-1].children.append(node)
        else:
            self.roots.append(node)

        self._stack.append(node)
        return True

    def handle_return(self, frame: FrameType, retval: object) -> None:
        if self.disabled or not self._stack:
            return

        node = self._stack[-1]
        code = frame.f_code

        # Make sure we are popping the right frame.
        if node.name != code.co_name:
            for idx in range(len(self._stack) - 1, -1, -1):
                if self._stack[idx].name == code.co_name:
                    node = self._stack[idx]
                    self._stack = self._stack[:idx]
                    break
            else:
                return
        else:
            self._stack.pop()

        node.end = time.perf_counter()
        node.elapsed = node.end - node.start
        # Only set return_value if no exception was recorded for this node.
        if node.exception is None:
            node.return_value = self._safe_repr(retval)

    def handle_exception(self, frame: FrameType, exc_info: Any) -> None:
        """Record exception information, never raising errors."""
        if self.disabled or not self._stack:
            return
        try:
            exc_type, exc_value, _tb = exc_info
            node = self._stack[-1]
            try:
                node.exception = f"{exc_type.__name__}: {exc_value}"
            except Exception:
                node.exception = "<exception repr failed>"
        except Exception:
            # Catch-all: never let exception handling crash the traced code
            pass


# ---------------------------------------------------------------------------
# Trace hook (installed via sys.settrace)
# ---------------------------------------------------------------------------

# We keep a lock so that install/uninstall of sys.settrace is serialised
# across threads, but the hot-path callback itself is lock-free.
_trace_lock = threading.Lock()
_trace_refcount = 0
_previous_trace: Any = None


def _local_trace(frame: FrameType, event: str, arg: Any) -> Any:
    """Per-frame trace function handling return and exception events."""
    collector = _active_collector.get()
    if collector is None:
        return _local_trace
    if event == "return":
        collector.handle_return(frame, arg)
    elif event == "exception":
        collector.handle_exception(frame, arg)
    # Return ourselves to keep tracing this frame.  Returning None for
    # 'line' events would disable tracing for the rest of the frame, so
    # we always return the callback.
    return _local_trace


def _global_trace(frame: FrameType, event: str, arg: Any) -> Any:
    """Global trace function installed via sys.settrace.

    Only handles 'call' events.  Returns _local_trace for frames we want
    to track (so we get their return/exception events), or None to skip.
    """
    if event != "call":
        return None
    collector = _active_collector.get()
    if collector is None:
        return None
    recorded = collector.handle_call(frame)
    return _local_trace if recorded else None


def _install_trace() -> None:
    global _trace_refcount, _previous_trace
    with _trace_lock:
        if _trace_refcount == 0:
            _previous_trace = sys.gettrace()
            sys.settrace(_global_trace)
            threading.settrace(_global_trace)
        _trace_refcount += 1


def _uninstall_trace() -> None:
    global _trace_refcount, _previous_trace
    with _trace_lock:
        _trace_refcount -= 1
        if _trace_refcount <= 0:
            _trace_refcount = 0
            sys.settrace(_previous_trace)
            threading.settrace(None)  # type: ignore[arg-type]
            _previous_trace = None


# ---------------------------------------------------------------------------
# Public API: the trace() context manager
# ---------------------------------------------------------------------------

class trace:
    """Opt-in tracing context manager for a single execution scope.

    Supports both synchronous and asynchronous usage::

        with trace() as t:
            ...
        print(t.tree())

        async with trace() as t:
            await ...
        t.to_json("trace.json")

    Parameters
    ----------
    ignore_modules:
        Module name prefixes to exclude from the trace.
    max_depth:
        Maximum call nesting depth to record.  Deeper calls are silently
        skipped.
    max_calls:
        Maximum total calls to record.  When exceeded the trace is frozen
        to prevent runaway overhead.
    max_repr:
        Maximum character length for repr() of arguments and return values.
    max_time:
        Maximum trace duration in seconds. When exceeded, tracing stops
        to prevent runaway resource usage in production.
    """

    def __init__(
        self,
        *,
        ignore_modules: Optional[list[str]] = None,
        max_depth: int = _DEFAULT_MAX_DEPTH,
        max_calls: int = _DEFAULT_MAX_CALLS,
        max_repr: int = _DEFAULT_MAX_REPR,
        max_time: float = _DEFAULT_MAX_TIME,
        cache: bool = True,
        cache_dir: Optional[Union[str, Path]] = None,
        label: Optional[str] = None,
    ) -> None:
        self._config = TraceConfig(
            ignore_modules=tuple(ignore_modules or []),
            max_depth=max_depth,
            max_calls=max_calls,
            max_repr=max_repr,
            max_time=max_time,
        )
        self._collector: Optional[_Collector] = None
        self._token: Any = None
        self._cache = cache
        self._cache_dir_base = cache_dir
        self._cache_path: Optional[Path] = None
        self._label = label
        self._start_wall: Optional[str] = None
        # Generate unique trace ID for correlation
        import uuid
        self._trace_id = str(uuid.uuid4())[:8]

    # ------------------------------------------------------------------
    # Sync context manager
    # ------------------------------------------------------------------

    def __enter__(self) -> "trace":
        self._collector = _Collector(self._config, self._trace_id)
        self._token = _active_collector.set(self._collector)
        self._start_wall = datetime.datetime.now().isoformat()
        _install_trace()
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        _uninstall_trace()
        if self._token is not None:
            _active_collector.reset(self._token)
            self._token = None
        self._save_to_cache()

    # ------------------------------------------------------------------
    # Async context manager
    # ------------------------------------------------------------------

    async def __aenter__(self) -> "trace":
        return self.__enter__()

    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        self.__exit__(exc_type, exc_val, exc_tb)

    # ------------------------------------------------------------------
    # Decorator support
    # ------------------------------------------------------------------

    def __call__(self, func):
        """Enable use as a decorator: @trace() or @trace(label='name').
        
        Supports:
        - Regular functions and methods
        - Async functions
        - Generators and async generators
        - Static methods and class methods (apply @trace after @staticmethod/@classmethod)
        """
        import functools
        import inspect
        
        # Preserve metadata using functools.wraps
        if inspect.iscoroutinefunction(func):
            # Async function
            @functools.wraps(func)
            async def async_wrapper(*args, **kwargs):
                async with self:
                    return await func(*args, **kwargs)
            return async_wrapper
        
        elif inspect.isasyncgenfunction(func):
            # Async generator
            @functools.wraps(func)
            async def async_gen_wrapper(*args, **kwargs):
                async with self:
                    async for item in func(*args, **kwargs):
                        yield item
            return async_gen_wrapper
        
        elif inspect.isgeneratorfunction(func):
            # Generator function
            @functools.wraps(func)
            def gen_wrapper(*args, **kwargs):
                with self:
                    yield from func(*args, **kwargs)
            return gen_wrapper
        
        else:
            # Regular sync function or method
            @functools.wraps(func)
            def sync_wrapper(*args, **kwargs):
                with self:
                    return func(*args, **kwargs)
            return sync_wrapper

    # ------------------------------------------------------------------
    # Query methods
    # ------------------------------------------------------------------

    @property
    def call_count(self) -> int:
        """Number of calls recorded so far."""
        if self._collector is None:
            return 0
        return self._collector.call_count

    @property
    def was_limited(self) -> bool:
        """True if the trace was cut short because a limit was exceeded."""
        if self._collector is None:
            return False
        return self._collector.disabled

    def tree(self) -> str:
        """Return a human-readable ASCII call tree with timing information."""
        if self._collector is None:
            return "<trace not started>"
        if not self._collector.roots:
            return "<no calls captured>"
        return render_tree(self._collector.roots)

    def to_json(self, path: Union[str, Path, TextIO]) -> None:
        """Export the trace to a JSON file.

        Parameters
        ----------
        path:
            A file path (str or Path) or a writable file object.
        """
        if self._collector is None:
            data: list[dict[str, Any]] = []
        else:
            data = [r.to_dict() for r in self._collector.roots]

        payload: dict[str, Any] = {
            "tracepatch_version": "0.3.3",
            "timestamp": self._start_wall or datetime.datetime.now().isoformat(),
            "label": self._label,
            "call_count": self.call_count,
            "was_limited": self.was_limited,
            "config": {
                "max_depth": self._config.max_depth,
                "max_calls": self._config.max_calls,
                "max_repr": self._config.max_repr,
                "ignore_modules": list(self._config.ignore_modules),
            },
            "trace": data,
        }

        if isinstance(path, (str, Path)):
            with open(path, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, indent=2)
        else:
            json.dump(payload, path, indent=2)

    @property
    def roots(self) -> list[TraceNode]:
        """Direct access to the root TraceNode list."""
        if self._collector is None:
            return []
        return self._collector.roots

    @property
    def cache_path(self) -> Optional[Path]:
        """Path to the cached JSON file, or None if caching was disabled."""
        return self._cache_path

    # ------------------------------------------------------------------
    # Cache helpers
    # ------------------------------------------------------------------

    def _save_to_cache(self) -> None:
        """Persist the trace to .tracepatch_cache/ as a timestamped JSON log."""
        if not self._cache:
            return
        if self._collector is None or not self._collector.roots:
            return
        try:
            cache_dir = _ensure_cache_dir(self._cache_dir_base)
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
            slug = ""
            if self._label:
                # Sanitise the label for use in a filename.
                safe = "".join(
                    c if c.isalnum() or c in ("_", "-") else "_"
                    for c in self._label
                )
                slug = f"_{safe}"
            filename = f"trace_{ts}{slug}.json"
            path = cache_dir / filename
            self.to_json(path)
            self._cache_path = path
        except Exception:
            # Caching is best-effort; never crash the caller.
            pass

    # ------------------------------------------------------------------
    # Class methods: read back cached logs
    # ------------------------------------------------------------------

    @classmethod
    def logs(
        cls,
        cache_dir: Optional[Union[str, Path]] = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        """List recent trace logs from the .tracepatch_cache directory.

        Returns a list of dicts, each containing the log metadata and the
        file path.  The list is sorted newest-first.  Full trace data is
        not loaded; use ``trace.load(path)`` to read a complete log.

        Parameters
        ----------
        cache_dir:
            Parent directory containing .tracepatch_cache/.  Defaults to
            the current working directory.
        limit:
            Maximum number of entries to return.
        """
        parent = Path(cache_dir) if cache_dir is not None else Path.cwd()
        cache = parent / _CACHE_DIR_NAME
        if not cache.is_dir():
            return []

        entries: list[dict[str, Any]] = []
        for p in sorted(cache.glob("trace_*.json"), reverse=True):
            if len(entries) >= limit:
                break
            try:
                with open(p, "r", encoding="utf-8") as fh:
                    data = json.load(fh)
                entries.append({
                    "file": str(p),
                    "timestamp": data.get("timestamp"),
                    "label": data.get("label"),
                    "call_count": data.get("call_count", 0),
                    "was_limited": data.get("was_limited", False),
                })
            except Exception:
                continue
        return entries

    @classmethod
    def load(cls, path: Union[str, Path]) -> dict[str, Any]:
        """Load a complete trace log from a JSON file.

        Parameters
        ----------
        path:
            Path to a trace JSON file (as returned by ``trace.logs()``
            or ``t.cache_path``).

        Returns
        -------
        The full JSON contents as a dict.
        """
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
