"""Internal implementation of the tracepatch tracing engine."""

from __future__ import annotations

import datetime
import json
import sys
import threading
import time
from contextvars import ContextVar
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, TextIO

if TYPE_CHECKING:
    from types import FrameType

# ---------------------------------------------------------------------------
# Cache directory management
# ---------------------------------------------------------------------------

_CACHE_DIR_NAME = ".tracepatch"
_TRACES_SUBDIR = "traces"
_CACHE_GITIGNORE = "# Auto-generated by tracepatch. Do not edit.\n*\n"
_CACHE_README = """This directory is managed by tracepatch.

traces/     — JSON trace logs produced by trace() context managers.
state.json  — Setup/cleanup state for *tph run* / *tph clean*.

The traces/ subdirectory is git-ignored by default so trace logs
are never committed.  This top-level directory (and state.json)
*should* be committed.

You can read these logs with:

    from tracepatch import trace
    for entry in trace.logs():
        print(entry["file"], "-", entry["call_count"], "calls")

Or open any file directly — they are plain JSON.
"""


def _ensure_cache_dir(base: str | Path | None = None) -> Path:
    """Create the ``.tracepatch/traces/`` directory tree if needed.

    The layout is::

        .tracepatch/
        ├── README.md
        ├── state.json   (managed elsewhere)
        └── traces/
            └── .gitignore   (contains ``*``)

    Parameters
    ----------
    base:
        Parent directory for ``.tracepatch``, or the data directory
        itself.  Defaults to the current working directory.

    Returns
    -------
    Path
        Path to the ``traces/`` subdirectory where JSON logs are stored.
    """
    if base is None:
        parent = Path.cwd()
        data_dir = parent / _CACHE_DIR_NAME
    else:
        base_path = Path(base)
        # Accept both the parent and the data dir itself.
        data_dir = base_path if base_path.name == _CACHE_DIR_NAME else base_path / _CACHE_DIR_NAME

    data_dir.mkdir(exist_ok=True)

    # README at .tracepatch/README.md
    readme = data_dir / "README.md"
    if not readme.exists():
        readme.write_text(_CACHE_README, encoding="utf-8")

    # traces/ subdirectory
    traces_dir = data_dir / _TRACES_SUBDIR
    traces_dir.mkdir(exist_ok=True)

    # .gitignore inside traces/ only
    gitignore = traces_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_CACHE_GITIGNORE, encoding="utf-8")

    return traces_dir


# ---------------------------------------------------------------------------
# Trace node: one captured call
# ---------------------------------------------------------------------------


@dataclass
class TraceNode:
    """A single captured function call, forming a tree via children."""

    name: str
    module: str
    args: str
    return_value: str | None = None
    exception: str | None = None
    start: float = 0.0
    end: float = 0.0
    elapsed: float = 0.0
    children: list[TraceNode] = field(default_factory=list)
    depth: int = 0
    file: str | None = None
    lineno: int | None = None
    memory_delta_kb: float | None = None

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Return a plain dict suitable for JSON serialisation."""
        d: dict[str, Any] = {
            "name": self.name,
            "module": self.module,
            "args": self.args,
            "return_value": self.return_value,
            "start": self.start,
            "end": self.end,
            "elapsed_ms": round(self.elapsed * 1000, 4),
        }
        if self.file is not None:
            d["file"] = self.file
        if self.lineno is not None:
            d["lineno"] = self.lineno
        if self.exception is not None:
            d["exception"] = self.exception
        if self.memory_delta_kb is not None:
            d["memory_delta_kb"] = round(self.memory_delta_kb, 2)
        if self.children:
            d["children"] = [c.to_dict() for c in self.children]
        return d


# ---------------------------------------------------------------------------
# Trace summary: lightweight statistics computed from a TraceNode tree
# ---------------------------------------------------------------------------


@dataclass
class TraceSummary:
    """Pre-computed statistics for a trace.

    Attributes
    ----------
    call_count:
        Total number of calls in the tree.
    max_depth_reached:
        Maximum nesting depth observed.
    unique_functions:
        Set of ``module.name`` strings for every unique function seen.
    unique_modules:
        Set of module names.
    total_duration_ms:
        Sum of root-node elapsed times in milliseconds.
    slowest_call_ms:
        Elapsed time of the single slowest call in milliseconds.
    slowest_call_name:
        ``module.name`` of the slowest call, or ``""`` if no calls.
    most_called:
        Top-10 most frequently called functions as ``(name, count)`` pairs,
        sorted descending by count.
    """

    call_count: int = 0
    max_depth_reached: int = 0
    unique_functions: set[str] = field(default_factory=set)
    unique_modules: set[str] = field(default_factory=set)
    total_duration_ms: float = 0.0
    slowest_call_ms: float = 0.0
    slowest_call_name: str = ""
    most_called: list[tuple[str, int]] = field(default_factory=list)

    @property
    def unique_function_count(self) -> int:
        """Number of unique functions in the trace."""
        return len(self.unique_functions)

    @property
    def unique_module_count(self) -> int:
        """Number of unique modules in the trace."""
        return len(self.unique_modules)

    @classmethod
    def from_roots(cls, roots: list[TraceNode]) -> TraceSummary:
        """Compute summary statistics from a list of root ``TraceNode``s.

        Parameters
        ----------
        roots:
            Root-level trace nodes.

        Returns
        -------
        TraceSummary
        """
        summary = cls()
        call_counts: dict[str, int] = {}
        slowest_ms = 0.0
        slowest_name = ""
        max_depth = 0

        def _walk(node: TraceNode, depth: int) -> None:
            nonlocal slowest_ms, slowest_name, max_depth
            summary.call_count += 1
            if depth > max_depth:
                max_depth = depth
            fqn = f"{node.module}.{node.name}" if node.module else node.name
            summary.unique_functions.add(fqn)
            if node.module:
                summary.unique_modules.add(node.module)
            call_counts[fqn] = call_counts.get(fqn, 0) + 1
            elapsed_ms = node.elapsed * 1000
            if elapsed_ms > slowest_ms:
                slowest_ms = elapsed_ms
                slowest_name = fqn
            for child in node.children:
                _walk(child, depth + 1)

        for root in roots:
            summary.total_duration_ms += root.elapsed * 1000
            _walk(root, 0)

        summary.max_depth_reached = max_depth
        summary.slowest_call_ms = slowest_ms
        summary.slowest_call_name = slowest_name
        summary.most_called = sorted(
            call_counts.items(), key=lambda x: x[1], reverse=True
        )[:10]
        return summary


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_DEFAULT_MAX_REPR = 120
_DEFAULT_MAX_DEPTH = 30
_DEFAULT_MAX_CALLS = 10_000
_DEFAULT_MAX_TIME = 60.0  # seconds


@dataclass(frozen=True)
class TraceConfig:
    """Immutable configuration for a single trace session.

    Attributes
    ----------
    ignore_modules:
        Module prefixes to exclude from tracing.
    include_modules:
        When non-empty, only modules matching these prefixes are traced.
    max_depth:
        Maximum call-stack nesting depth.
    max_calls:
        Maximum total calls before tracing is disabled.
    max_repr:
        Maximum character length for ``repr()`` output.
    max_time:
        Maximum trace duration in seconds.
    """

    ignore_modules: tuple[str, ...] = ()
    include_modules: tuple[str, ...] = ()
    max_depth: int = _DEFAULT_MAX_DEPTH
    max_calls: int = _DEFAULT_MAX_CALLS
    max_repr: int = _DEFAULT_MAX_REPR
    max_time: float = _DEFAULT_MAX_TIME
    track_memory: bool = False
    sample: float | None = None


# ---------------------------------------------------------------------------
# ASCII tree renderer
# ---------------------------------------------------------------------------


def _format_elapsed(seconds: float) -> str:
    """Human-friendly elapsed time string."""
    ms = seconds * 1000
    if ms < 1:
        return f"{seconds * 1_000_000:.0f}us"
    if ms < 1000:
        return f"{ms:.2f}ms"
    return f"{seconds:.3f}s"


def render_tree(
    roots: list[TraceNode],
    *,
    style: str = "ascii",
    show_args: bool = True,
    show_return: bool = True,
    show_source: bool = False,
    show_self_time: bool = False,
) -> str:
    """Render a list of root ``TraceNode``s as a readable call tree.

    Parameters
    ----------
    roots:
        Top-level trace nodes to render.
    style:
        ``"ascii"`` for plain ASCII connectors, ``"unicode"`` for
        box-drawing characters, or ``"ansi"`` for box-drawing with
        dim-coloured connectors.
    show_args:
        Include function arguments in the output.
    show_return:
        Include return values / exceptions in the output.
    show_source:
        Include source file and line number for each call.
    show_self_time:
        Show self-time (total minus children) alongside the total elapsed time.

    Returns
    -------
    str
        The rendered multi-line tree string.
    """
    dim = "\033[2m"
    reset = "\033[0m"
    if style == "unicode":
        last_conn = "\u2514\u2500 "
        mid_conn = "\u251c\u2500 "
        cont = "\u2502  "
        space = "   "
    elif style == "ansi":
        last_conn = f"{dim}\u2514\u2500 {reset}"
        mid_conn = f"{dim}\u251c\u2500 {reset}"
        cont = f"{dim}\u2502  {reset}"
        space = "   "
    else:
        last_conn = "\u2514\u2500\u2500 "
        mid_conn = "\u251c\u2500\u2500 "
        cont = "\u2502   "
        space = "    "

    lines: list[str] = []

    def _walk(node: TraceNode, prefix: str, is_last: bool) -> None:
        connector = last_conn if is_last else mid_conn
        ret = ""
        if show_return:
            if node.exception is not None:
                ret = f" !! {node.exception}"
            elif node.return_value is not None:
                ret = f" -> {node.return_value}"

        timing = _format_elapsed(node.elapsed)
        if show_self_time and node.children:
            child_sum = sum(c.elapsed for c in node.children)
            self_sec = max(0.0, node.elapsed - child_sum)
            timing = f"{timing} / self: {_format_elapsed(self_sec)}"

        # Memory delta annotation (only when tracking enabled)
        mem_str = ""
        if node.memory_delta_kb is not None:
            delta = node.memory_delta_kb
            mem_str = f", {delta / 1024:+.1f} MB" if abs(delta) >= 1024 else f", {delta:+.1f} KB"

        args_part = f"({node.args})" if show_args else "()"
        label = f"{node.module}.{node.name}{args_part}{ret}  [{timing}{mem_str}]"
        if show_source and node.file and node.lineno is not None:
            label += f"  ({node.file}:{node.lineno})"
        lines.append(f"{prefix}{connector}{label}")

        extension = space if is_last else cont
        child_prefix = prefix + extension
        for i, child in enumerate(node.children):
            _walk(child, child_prefix, i == len(node.children) - 1)

    for i, root in enumerate(roots):
        _walk(root, "", i == len(roots) - 1)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tree manipulation utilities
# ---------------------------------------------------------------------------


def _count_nodes(nodes: list[TraceNode]):
    """Generator that yields every node in *nodes* recursively."""
    for node in nodes:
        yield node
        yield from _count_nodes(node.children)


def _filter_node(node: TraceNode, pattern: str, exclude: bool = False) -> bool:
    """Check if *node* matches *pattern*.

    Parameters
    ----------
    node:
        The ``TraceNode`` to check.
    pattern:
        Module pattern to match (e.g. ``"app.*"``).
    exclude:
        If ``True``, *exclude* matches; otherwise *include* only matches.

    Returns
    -------
    bool
        ``True`` if the node should be kept.
    """
    import fnmatch

    matches = fnmatch.fnmatch(node.module, pattern)
    return not matches if exclude else matches


def _apply_filter(nodes: list[TraceNode], pattern: str) -> list[TraceNode]:
    """Apply *pattern* to a list of trace nodes recursively.

    Parameters
    ----------
    nodes:
        Nodes to filter.
    pattern:
        Filter string — prefix with ``!`` to exclude.

    Returns
    -------
    list[TraceNode]
    """
    exclude = pattern.startswith("!")
    if exclude:
        pattern = pattern[1:]

    filtered: list[TraceNode] = []
    for node in nodes:
        if _filter_node(node, pattern, exclude):
            new_node = TraceNode(
                name=node.name,
                module=node.module,
                args=node.args,
                return_value=node.return_value,
                exception=node.exception,
                start=node.start,
                end=node.end,
                elapsed=node.elapsed,
                children=_apply_filter(node.children, pattern),
                depth=node.depth,
                file=node.file,
                lineno=node.lineno,
            )
            filtered.append(new_node)
        else:
            filtered.extend(_apply_filter(node.children, pattern))

    return filtered


def _limit_depth(
    nodes: list[TraceNode],
    max_depth: int,
    current_depth: int = 0,
) -> list[TraceNode]:
    """Limit trace tree depth to *max_depth* levels.

    Parameters
    ----------
    nodes:
        Nodes to truncate.
    max_depth:
        Maximum depth to include.
    current_depth:
        Current recursion depth (used internally).

    Returns
    -------
    list[TraceNode]
    """
    if current_depth >= max_depth:
        return []

    limited: list[TraceNode] = []
    for node in nodes:
        child_count = len(node.children)
        limited_children = _limit_depth(node.children, max_depth, current_depth + 1)

        new_node = TraceNode(
            name=node.name,
            module=node.module,
            args=node.args,
            return_value=node.return_value,
            exception=node.exception,
            start=node.start,
            end=node.end,
            elapsed=node.elapsed,
            children=limited_children,
            depth=node.depth,
            file=node.file,
            lineno=node.lineno,
        )

        if current_depth + 1 >= max_depth and child_count > 0:
            truncated_node = TraceNode(
                name=f"[{child_count} nested calls...]",
                module="",
                args="",
                start=0,
                end=0,
                elapsed=0,
                children=[],
                depth=node.depth + 1,
            )
            new_node.children.append(truncated_node)

        limited.append(new_node)

    return limited


def fold_repeated_calls(
    nodes: list[TraceNode],
    *,
    threshold: int = 3,
) -> list[TraceNode]:
    """Fold consecutive sibling calls to the same function.

    When *threshold* or more consecutive siblings share the same
    ``name`` and ``module``, they are replaced by a single synthetic
    node annotated with count, average, min, max, and total timing.

    Parameters
    ----------
    nodes:
        Sibling nodes at one level of the tree.
    threshold:
        Minimum run length to trigger folding (default ``3``).

    Returns
    -------
    list[TraceNode]
        New node list with runs folded.  Children of each node are
        also folded recursively.
    """
    if not nodes:
        return []

    result: list[TraceNode] = []
    i = 0
    while i < len(nodes):
        run_start = i
        key = (nodes[i].name, nodes[i].module)
        while i < len(nodes) and (nodes[i].name, nodes[i].module) == key:
            i += 1
        run = nodes[run_start:i]

        if len(run) >= threshold:
            total_elapsed = sum(n.elapsed for n in run)
            avg_elapsed = total_elapsed / len(run)
            min_elapsed = min(n.elapsed for n in run)
            max_elapsed = max(n.elapsed for n in run)
            # Merge all children from the run
            merged_children: list[TraceNode] = []
            for n in run:
                merged_children.extend(n.children)
            folded = TraceNode(
                name=run[0].name,
                module=run[0].module,
                args=f"...  [\u00d7{len(run)}]  "
                f"[avg: {_format_elapsed(avg_elapsed)}, "
                f"min: {_format_elapsed(min_elapsed)}, "
                f"max: {_format_elapsed(max_elapsed)}]",
                start=run[0].start,
                end=run[-1].end,
                elapsed=total_elapsed,
                children=fold_repeated_calls(merged_children, threshold=threshold),
                depth=run[0].depth,
                file=run[0].file,
                lineno=run[0].lineno,
            )
            result.append(folded)
        else:
            for n in run:
                folded_node = TraceNode(
                    name=n.name,
                    module=n.module,
                    args=n.args,
                    return_value=n.return_value,
                    exception=n.exception,
                    start=n.start,
                    end=n.end,
                    elapsed=n.elapsed,
                    children=fold_repeated_calls(n.children, threshold=threshold),
                    depth=n.depth,
                    file=n.file,
                    lineno=n.lineno,
                )
                result.append(folded_node)

    return result


def render_summary_header(
    roots: list[TraceNode],
    *,
    label: str | None = None,
) -> str:
    """Render a statistics summary header for a trace tree.

    Parameters
    ----------
    roots:
        Top-level trace nodes.
    label:
        Optional trace label to display.

    Returns
    -------
    str
        Multi-line summary string.
    """
    summary = TraceSummary.from_roots(roots)
    width = 72
    rule = "\u2500" * width
    parts: list[str] = []
    if label:
        parts.append(f"Trace: {label}")
    parts.append(rule)
    left1 = f"Recorded:     {summary.call_count} calls across {len(summary.unique_modules)} modules"
    right1 = f"Duration: {_format_elapsed(summary.total_duration_ms / 1000)}"
    parts.append(f"{left1:<40}| {right1}")
    left2 = f"Max depth:    {summary.max_depth_reached} levels"
    right2 = f"Unique functions: {len(summary.unique_functions)}"
    parts.append(f"{left2:<40}| {right2}")
    if summary.slowest_call_name:
        left3 = f"Slowest:      {summary.slowest_call_name} [{_format_elapsed(summary.slowest_call_ms / 1000)}]"
    else:
        left3 = "Slowest:      —"
    if summary.most_called:
        mc_name, mc_count = summary.most_called[0]
        right3 = f"Most called: {mc_name} [\u00d7{mc_count}]"
    else:
        right3 = "Most called: —"
    parts.append(f"{left3:<40}| {right3}")
    parts.append(rule)
    return "\n".join(parts)


def collapse_tree(
    nodes: list[TraceNode],
    *,
    max_depth: int = 4,
) -> list[TraceNode]:
    """Auto-collapse subtrees beyond *max_depth*.

    Subtrees deeper than *max_depth* are replaced with a single
    synthetic node showing the hidden call count and total time.

    Parameters
    ----------
    nodes:
        Top-level trace nodes.
    max_depth:
        Depth at which to collapse (default ``4``).

    Returns
    -------
    list[TraceNode]
    """

    def _count_and_time(node: TraceNode) -> tuple[int, float]:
        """Return (total_nodes, total_elapsed) under *node*."""
        count = 1
        elapsed = node.elapsed
        for child in node.children:
            c, _e = _count_and_time(child)
            count += c
            elapsed = max(elapsed, node.elapsed)  # parent already includes children
        return count, elapsed

    def _collapse(node_list: list[TraceNode], depth: int) -> list[TraceNode]:
        if depth >= max_depth:
            collapsed: list[TraceNode] = []
            for n in node_list:
                child_count, _ = _count_and_time(n)
                collapsed.append(
                    TraceNode(
                        name=n.name,
                        module=n.module,
                        args=n.args,
                        return_value=n.return_value,
                        exception=n.exception,
                        start=n.start,
                        end=n.end,
                        elapsed=n.elapsed,
                        children=[
                            TraceNode(
                                name=f"[+{child_count - 1} more calls, {_format_elapsed(n.elapsed)} total]",
                                module="",
                                args="",
                                start=0,
                                end=0,
                                elapsed=0,
                                children=[],
                                depth=n.depth + 1,
                            )
                        ]
                        if n.children
                        else [],
                        depth=n.depth,
                        file=n.file,
                        lineno=n.lineno,
                    )
                )
            return collapsed

        result: list[TraceNode] = []
        for n in node_list:
            result.append(
                TraceNode(
                    name=n.name,
                    module=n.module,
                    args=n.args,
                    return_value=n.return_value,
                    exception=n.exception,
                    start=n.start,
                    end=n.end,
                    elapsed=n.elapsed,
                    children=_collapse(n.children, depth + 1),
                    depth=n.depth,
                    file=n.file,
                    lineno=n.lineno,
                )
            )
        return result

    return _collapse(nodes, 0)


def _dict_to_node(d: dict[str, Any]) -> TraceNode:
    """Convert a dict (from JSON) back to a ``TraceNode``."""
    node = TraceNode(
        name=d.get("name", ""),
        module=d.get("module", ""),
        args=d.get("args", ""),
        return_value=d.get("return_value"),
        exception=d.get("exception"),
        start=d.get("start", 0.0),
        end=d.get("end", 0.0),
        elapsed=d.get("elapsed_ms", 0.0) / 1000.0,
        children=[],
        depth=0,
        file=d.get("file"),
        lineno=d.get("lineno"),
    )
    for child_dict in d.get("children", []):
        node.children.append(_dict_to_node(child_dict))
    return node


def nodes_to_json(roots: list[TraceNode]) -> str:
    """Convert trace nodes to a JSON string.

    Parameters
    ----------
    roots:
        Top-level trace nodes.

    Returns
    -------
    str
        Indented JSON representation.
    """

    def _node_to_dict(node: TraceNode) -> dict[str, Any]:
        return {
            "name": node.name,
            "module": node.module,
            "args": node.args,
            "return_value": node.return_value,
            "exception": node.exception,
            "start": node.start,
            "end": node.end,
            "elapsed_ms": round(node.elapsed * 1000, 4),
            "children": [_node_to_dict(c) for c in node.children] if node.children else [],
        }

    return json.dumps([_node_to_dict(r) for r in roots], indent=2)


# ---------------------------------------------------------------------------
# Context-local trace collector (isolates async tasks)
# ---------------------------------------------------------------------------

_active_collector: ContextVar[_Collector | None] = ContextVar(
    "tracepatch_active_collector",
    default=None,
)


class _Collector:
    """Accumulates trace nodes for one execution context.

    Thread-safety: each collector is accessed only from its own context.
    The profile callback checks the ContextVar, so different async tasks
    get different collectors even when sharing an event loop thread.
    """

    def __init__(self, config: TraceConfig, trace_id: str) -> None:
        self.config = config
        self.roots: list[TraceNode] = []
        self.call_count: int = 0
        self.disabled: bool = False
        self.trace_id = trace_id  # Unique ID for correlation in multi-threaded scenarios
        self.start_time = time.perf_counter()  # For max_time enforcement

        # Stack of (node, depth) tracking the open call frames.
        self._stack: list[TraceNode] = []
        # Track seen objects to detect circular references
        self._seen_objects: set[int] = set()
        # Track objects that have already warned about repr failures.
        # Memory: bounded by max_calls and max_time limits, cleaned up on __exit__.
        # Thread-safety: not needed, each collector is context-local (ContextVar).
        self._warned_objects: set[int] = set()
        # Memory tracking: maps node id() -> traced memory bytes at call entry.
        # Only populated when config.track_memory is True.
        self._memory_at_call: dict[int, int] = {}

    # ------------------------------------------------------------------
    # safe repr
    # ------------------------------------------------------------------

    def _safe_repr(self, obj: object) -> str:
        """Safely create a string representation, handling errors and circular refs."""
        limit = self.config.max_repr
        try:
            # Detect circular references
            obj_id = id(obj)
            if obj_id in self._seen_objects:
                return "<circular reference>"

            # Track this object temporarily
            self._seen_objects.add(obj_id)

            try:
                r = repr(obj)
            except Exception as e:
                # Only log the error once per unique object to avoid noise
                if obj_id not in self._warned_objects:
                    self._warned_objects.add(obj_id)
                    try:
                        import sys

                        print(f"[tracepatch] repr failed: {type(e).__name__}", file=sys.stderr)
                    except Exception:
                        pass
                return "<unprintable>"
            finally:
                # Always clean up
                self._seen_objects.discard(obj_id)

            if len(r) > limit:
                return r[: limit - 3] + "..."
            return r
        except Exception:
            # Catch-all: never let repr issues crash the traced code
            return "<error>"

    # ------------------------------------------------------------------
    # Trace callback events
    # ------------------------------------------------------------------

    # Modules that are always silently skipped regardless of configuration.
    # These are either tracepatch internals, noisy stdlib serialisation
    # internals that produce massive subtrees whenever JSON/repr is used,
    # or test-infrastructure modules that produce confusing noise.
    _BUILTIN_IGNORE_PREFIXES: tuple[str, ...] = (
        "tracepatch",
        "threading",
        "json",  # json.encoder/_iterencode* produce huge subtrees
        "unittest.mock",  # MagicMock attribute chains explode repr calls
    )

    def _should_ignore(self, frame: FrameType) -> bool:
        """Return ``True`` if *frame* should be skipped.

        Checks in order:
        1. Built-in ignore prefixes (tracepatch internals, etc.).
        2. User-specified ``ignore_modules``.
        3. If ``include_modules`` is non-empty, anything **not** matching
           an include prefix is ignored.

        Parameters
        ----------
        frame:
            The call frame to evaluate.

        Returns
        -------
        bool
        """
        module = frame.f_globals.get("__name__", "") or ""
        for prefix in self._BUILTIN_IGNORE_PREFIXES:
            if module == prefix or module.startswith(prefix + "."):
                return True
        for prefix in self.config.ignore_modules:
            if module == prefix or module.startswith(prefix + "."):
                return True
        # Allowlist check — if include_modules is non-empty, reject anything
        # that doesn't match a listed prefix.
        if self.config.include_modules:
            for prefix in self.config.include_modules:
                if module == prefix or module.startswith(prefix + "."):
                    return False
            return True
        return False

    def handle_call(self, frame: FrameType) -> bool:
        """Process a call event.  Returns True if the call was recorded."""
        if self.disabled:
            return False

        # Statistical sampling — skip calls randomly when sample < 1.0.
        if self.config.sample is not None:
            import random

            if random.random() > self.config.sample:
                return False

        # Enforce max_time
        if time.perf_counter() - self.start_time > self.config.max_time:
            self.disabled = True
            return False

        if self._should_ignore(frame):
            return False

        code = frame.f_code
        module = frame.f_globals.get("__name__", "") or ""
        depth = len(self._stack)

        # Enforce max_depth.
        if depth >= self.config.max_depth:
            return False

        # Enforce max_calls.
        self.call_count += 1
        if self.call_count > self.config.max_calls:
            self.disabled = True
            return False

        # Capture arguments via frame locals.
        # f_locals is a snapshot; we only capture it at call time.
        args_dict = frame.f_locals.copy()
        args_parts: list[str] = []
        for param, val in args_dict.items():
            args_parts.append(f"{param}={self._safe_repr(val)}")
        args_str = ", ".join(args_parts)
        if len(args_str) > self.config.max_repr:
            args_str = args_str[: self.config.max_repr - 3] + "..."

        node = TraceNode(
            name=code.co_name,
            module=module,
            args=args_str,
            start=time.perf_counter(),
            depth=depth,
            file=code.co_filename,
            lineno=code.co_firstlineno,
        )

        if self._stack:
            self._stack[-1].children.append(node)
        else:
            self.roots.append(node)

        self._stack.append(node)

        # Record memory snapshot at call entry if tracking is enabled.
        if self.config.track_memory:
            import tracemalloc as _tm

            current, _peak = _tm.get_traced_memory()
            self._memory_at_call[id(node)] = current

        return True

    def handle_return(self, frame: FrameType, retval: object) -> None:
        if self.disabled or not self._stack:
            return

        node = self._stack[-1]
        code = frame.f_code

        # Make sure we are popping the right frame.
        if node.name != code.co_name:
            for idx in range(len(self._stack) - 1, -1, -1):
                if self._stack[idx].name == code.co_name:
                    node = self._stack[idx]
                    self._stack = self._stack[:idx]
                    break
            else:
                return
        else:
            self._stack.pop()

        node.end = time.perf_counter()
        node.elapsed = node.end - node.start
        # Only set return_value if no exception was recorded for this node.
        if node.exception is None:
            node.return_value = self._safe_repr(retval)

        # Compute memory delta if tracking is enabled.
        node_id = id(node)
        if self.config.track_memory and node_id in self._memory_at_call:
            import tracemalloc as _tm

            current, _peak = _tm.get_traced_memory()
            delta_bytes = current - self._memory_at_call.pop(node_id)
            node.memory_delta_kb = delta_bytes / 1024

    def handle_exception(self, frame: FrameType, exc_info: Any) -> None:
        """Record exception information, never raising errors."""
        if self.disabled or not self._stack:
            return
        try:
            exc_type, exc_value, _tb = exc_info
            node = self._stack[-1]
            try:
                node.exception = f"{exc_type.__name__}: {exc_value}"
            except Exception:
                node.exception = "<exception repr failed>"
        except Exception:
            # Catch-all: never let exception handling crash the traced code
            pass


# ---------------------------------------------------------------------------
# Trace hook (installed via sys.settrace)
# ---------------------------------------------------------------------------

# We keep a lock so that install/uninstall of sys.settrace is serialised
# across threads, but the hot-path callback itself is lock-free.
_trace_lock = threading.Lock()
_trace_refcount = 0
_previous_trace: Any = None


def _local_trace(frame: FrameType, event: str, arg: Any) -> Any:
    """Per-frame trace function handling return and exception events."""
    collector = _active_collector.get()
    if collector is None:
        return _local_trace
    if event == "return":
        collector.handle_return(frame, arg)
    elif event == "exception":
        collector.handle_exception(frame, arg)
    # Return ourselves to keep tracing this frame.  Returning None for
    # 'line' events would disable tracing for the rest of the frame, so
    # we always return the callback.
    return _local_trace


def _global_trace(frame: FrameType, event: str, arg: Any) -> Any:
    """Global trace function installed via sys.settrace.

    Only handles 'call' events.  Returns _local_trace for frames we want
    to track (so we get their return/exception events), or None to skip.
    """
    if event != "call":
        return None
    collector = _active_collector.get()
    if collector is None:
        return None
    recorded = collector.handle_call(frame)
    return _local_trace if recorded else None


def _install_trace() -> None:
    global _trace_refcount, _previous_trace
    with _trace_lock:
        if _trace_refcount == 0:
            _previous_trace = sys.gettrace()
            sys.settrace(_global_trace)
            threading.settrace(_global_trace)
        _trace_refcount += 1


def _uninstall_trace() -> None:
    global _trace_refcount, _previous_trace
    with _trace_lock:
        _trace_refcount -= 1
        if _trace_refcount <= 0:
            _trace_refcount = 0
            sys.settrace(_previous_trace)
            threading.settrace(None)  # type: ignore[arg-type]
            _previous_trace = None


# ---------------------------------------------------------------------------
# Public API: the trace() context manager
# ---------------------------------------------------------------------------


class trace:
    """Opt-in tracing context manager for a single execution scope.

    Supports both synchronous and asynchronous usage::

        with trace() as t:
            ...
        print(t.tree())

        async with trace() as t:
            await ...
        t.to_json("trace.json")

    Parameters
    ----------
    ignore_modules:
        Module name prefixes to exclude from the trace.
    max_depth:
        Maximum call nesting depth to record.  Deeper calls are silently
        skipped.
    max_calls:
        Maximum total calls to record.  When exceeded the trace is frozen
        to prevent runaway overhead.
    max_repr:
        Maximum character length for repr() of arguments and return values.
    max_time:
        Maximum trace duration in seconds. When exceeded, tracing stops
        to prevent runaway resource usage in production.
    track_memory:
        When *True*, record per-call memory deltas using ``tracemalloc``.
        Has real overhead — never enable in production.  Off by default.
    sample:
        When set to a float between 0 and 1, only record that fraction
        of calls (statistical profiling).  ``None`` disables sampling.
    """

    def __init__(
        self,
        *,
        ignore_modules: list[str] | None = None,
        include_modules: list[str] | None = None,
        max_depth: int = _DEFAULT_MAX_DEPTH,
        max_calls: int = _DEFAULT_MAX_CALLS,
        max_repr: int = _DEFAULT_MAX_REPR,
        max_time: float = _DEFAULT_MAX_TIME,
        cache: bool = True,
        cache_dir: str | Path | None = None,
        label: str | None = None,
        track_memory: bool = False,
        sample: float | None = None,
    ) -> None:
        self._config = TraceConfig(
            ignore_modules=tuple(ignore_modules or []),
            include_modules=tuple(include_modules or []),
            max_depth=max_depth,
            max_calls=max_calls,
            max_repr=max_repr,
            max_time=max_time,
            track_memory=track_memory,
            sample=sample,
        )
        self._collector: _Collector | None = None
        self._token: Any = None
        self._cache = cache
        self._cache_dir_base = cache_dir
        self._cache_path: Path | None = None
        self._label = label
        self._start_wall: str | None = None
        self._started_tracemalloc: bool = False
        # Generate unique trace ID for correlation
        import uuid

        self._trace_id = str(uuid.uuid4())[:8]

    # ------------------------------------------------------------------
    # Sync context manager
    # ------------------------------------------------------------------

    def __enter__(self) -> trace:
        # Start tracemalloc if memory tracking is enabled.
        if self._config.track_memory:
            import tracemalloc as _tm

            if not _tm.is_tracing():
                _tm.start()
                self._started_tracemalloc = True
            else:
                self._started_tracemalloc = False
        else:
            self._started_tracemalloc = False

        self._collector = _Collector(self._config, self._trace_id)
        self._token = _active_collector.set(self._collector)
        self._start_wall = datetime.datetime.now().isoformat()
        _install_trace()
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        _uninstall_trace()
        if self._token is not None:
            _active_collector.reset(self._token)
            self._token = None
        self._save_to_cache()

        # Stop tracemalloc only if we started it.
        if self._started_tracemalloc:
            import tracemalloc as _tm

            _tm.stop()

    # ------------------------------------------------------------------
    # Async context manager
    # ------------------------------------------------------------------

    async def __aenter__(self) -> trace:
        return self.__enter__()

    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        self.__exit__(exc_type, exc_val, exc_tb)

    # ------------------------------------------------------------------
    # Decorator support
    # ------------------------------------------------------------------

    def __call__(self, func):
        """Enable use as a decorator: ``@trace()`` or ``@trace(label='name')``.

        Each invocation of the decorated function creates a **fresh** ``trace``
        instance so that calls are fully independent.

        Supports regular functions, async functions, generators, and async
        generators.

        Parameters
        ----------
        func:
            The function to wrap with tracing.

        Returns
        -------
        The wrapped function with the same signature and metadata.
        """
        import functools
        import inspect

        # Capture constructor kwargs so a fresh trace() can be built per call.
        init_kwargs: dict[str, Any] = {
            "ignore_modules": list(self._config.ignore_modules),
            "include_modules": list(self._config.include_modules),
            "max_depth": self._config.max_depth,
            "max_calls": self._config.max_calls,
            "max_repr": self._config.max_repr,
            "max_time": self._config.max_time,
            "cache": self._cache,
            "cache_dir": self._cache_dir_base,
            "label": self._label,
            "track_memory": self._config.track_memory,
            "sample": self._config.sample,
        }

        if inspect.iscoroutinefunction(func):

            @functools.wraps(func)
            async def async_wrapper(*args, **kwargs):
                async with trace(**init_kwargs):
                    return await func(*args, **kwargs)

            return async_wrapper

        elif inspect.isasyncgenfunction(func):

            @functools.wraps(func)
            async def async_gen_wrapper(*args, **kwargs):
                async with trace(**init_kwargs):
                    async for item in func(*args, **kwargs):
                        yield item

            return async_gen_wrapper

        elif inspect.isgeneratorfunction(func):

            @functools.wraps(func)
            def gen_wrapper(*args, **kwargs):
                with trace(**init_kwargs):
                    yield from func(*args, **kwargs)

            return gen_wrapper

        else:

            @functools.wraps(func)
            def sync_wrapper(*args, **kwargs):
                with trace(**init_kwargs):
                    return func(*args, **kwargs)

            return sync_wrapper

    # ------------------------------------------------------------------
    # Query methods
    # ------------------------------------------------------------------

    @property
    def call_count(self) -> int:
        """Number of calls recorded so far."""
        if self._collector is None:
            return 0
        return self._collector.call_count

    @property
    def was_limited(self) -> bool:
        """True if the trace was cut short because a limit was exceeded."""
        if self._collector is None:
            return False
        return self._collector.disabled

    def tree(self) -> str:
        """Return a human-readable ASCII call tree with timing information."""
        if self._collector is None:
            return "<trace not started>"
        if not self._collector.roots:
            return "<no calls captured>"
        return render_tree(self._collector.roots)

    def summary(self) -> TraceSummary:
        """Return pre-computed trace statistics.

        Works both inside and after the context manager has exited.

        Returns
        -------
        TraceSummary
        """
        if self._collector is None or not self._collector.roots:
            return TraceSummary()
        return TraceSummary.from_roots(self._collector.roots)

    def explain(self, *, verbose: bool = False) -> str:
        """Generate a narrative explanation of the trace.

        Detects patterns such as recursion, loops, slow calls, and
        exceptions, producing an educational summary.  No AI or LLM is
        used — all analysis is deterministic and template-based.

        Parameters
        ----------
        verbose:
            Include complexity hints when *True*.

        Returns
        -------
        str
        """
        from tracepatch._educational import explain as _explain

        return _explain(self.roots, verbose=verbose)

    def show(self) -> None:
        """Render the trace inline in a Jupyter notebook.

        When running inside a Jupyter notebook the trace is displayed as
        an interactive HTML tree using ``IPython.display.HTML``.  Outside
        a notebook the plain-text tree is printed to stdout.
        """
        from tracepatch._jupyter import show as _show

        _show(self)

    def to_json(self, path: str | Path | TextIO) -> None:
        """Export the trace to a JSON file.

        Parameters
        ----------
        path:
            A file path (str or Path) or a writable file object.
        """
        if self._collector is None:
            data: list[dict[str, Any]] = []
        else:
            data = [r.to_dict() for r in self._collector.roots]

        import platform as _platform
        import socket

        from tracepatch import __version__ as _lib_version

        # Compute summary statistics without requiring TraceSummary
        summary = self.summary()

        # Determine limit reason
        limit_reason = None
        if self._collector is not None and self._collector.disabled:
            elapsed = time.perf_counter() - self._collector.start_time
            if elapsed >= self._config.max_time:
                limit_reason = "max_time"
            elif self._collector.call_count > self._config.max_calls:
                limit_reason = "max_calls"

        # Compute total duration
        duration_ms = 0.0
        if self._collector is not None:
            for r in self._collector.roots:
                duration_ms += r.elapsed * 1000

        payload: dict[str, Any] = {
            "tracepatch_version": _lib_version,
            "schema_version": 1,
            "timestamp": self._start_wall or datetime.datetime.now().isoformat(),
            "label": self._label,
            "trace_id": self._trace_id,
            "hostname": socket.gethostname(),
            "python_version": _platform.python_version(),
            "platform": sys.platform,
            "working_directory": str(Path.cwd()),
            "duration_ms": round(duration_ms, 4),
            "call_count": self.call_count,
            "was_limited": self.was_limited,
            "limit_reason": limit_reason,
            "config": {
                "max_depth": self._config.max_depth,
                "max_calls": self._config.max_calls,
                "max_repr": self._config.max_repr,
                "max_time": self._config.max_time,
                "ignore_modules": list(self._config.ignore_modules),
                "include_modules": list(self._config.include_modules),
                "track_memory": self._config.track_memory,
                "sample": self._config.sample,
            },
            "stats": {
                "max_depth_reached": summary.max_depth_reached,
                "unique_functions": summary.unique_function_count,
                "unique_modules": summary.unique_module_count,
                "slowest_call_ms": round(summary.slowest_call_ms, 4),
                "slowest_call_name": summary.slowest_call_name,
            },
            "trace": data,
        }

        if isinstance(path, (str, Path)):
            with open(path, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, indent=2)
        else:
            json.dump(payload, path, indent=2)

    def to_flamegraph(self, path: str | Path) -> None:
        """Export the trace as a flamegraph SVG file.

        Each function call is rendered as a horizontal bar whose width
        is proportional to its total elapsed time, stacked vertically
        by call depth.  The output is a self-contained SVG with
        interactive tooltips.

        Parameters
        ----------
        path:
            File path to write the SVG to.
        """
        from tracepatch._flamegraph import nodes_to_flamegraph

        label = self._label or "Flamegraph"
        svg = nodes_to_flamegraph(self.roots, title=label)
        Path(path).write_text(svg, encoding="utf-8")

    @property
    def roots(self) -> list[TraceNode]:
        """Direct access to the root TraceNode list."""
        if self._collector is None:
            return []
        return self._collector.roots

    @property
    def cache_path(self) -> Path | None:
        """Path to the cached JSON file, or None if caching was disabled."""
        return self._cache_path

    # ------------------------------------------------------------------
    # Cache helpers
    # ------------------------------------------------------------------

    def _save_to_cache(self) -> None:
        """Persist the trace to ``.tracepatch/traces/`` as a timestamped JSON log.

        File naming convention: ``{label}_{YYYYMMDD}_{HHMMSS}_{short-id}.json``
        where *label* comes first for natural ``ls`` sorting.  If no label is
        set, ``trace`` is used as the prefix.
        """
        if not self._cache:
            return
        if self._collector is None or not self._collector.roots:
            return
        try:
            cache_dir = _ensure_cache_dir(self._cache_dir_base)
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            short_id = self._trace_id[:6]
            if self._label:
                safe = "".join(c if c.isalnum() or c in ("-",) else "-" for c in self._label)
                prefix = safe
            else:
                prefix = "trace"
            filename = f"{prefix}_{ts}_{short_id}.json"
            path = cache_dir / filename
            self.to_json(path)
            self._cache_path = path
        except Exception:
            # Caching is best-effort; never crash the caller.
            pass

    # ------------------------------------------------------------------
    # Class methods: read back cached logs
    # ------------------------------------------------------------------

    @classmethod
    def logs(
        cls,
        cache_dir: str | Path | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        """List recent trace logs from the ``.tracepatch/traces/`` directory.

        Returns a list of dicts, each containing the log metadata and the
        file path.  The list is sorted newest-first.  Full trace data is
        not loaded; use ``trace.load(path)`` to read a complete log.

        Parameters
        ----------
        cache_dir:
            Parent directory containing ``.tracepatch/``.  Defaults to
            the current working directory.
        limit:
            Maximum number of entries to return.
        """
        parent = Path(cache_dir) if cache_dir is not None else Path.cwd()
        # Look in .tracepatch/traces/
        traces = parent / _CACHE_DIR_NAME / _TRACES_SUBDIR
        if not traces.is_dir():
            # Backward compat: also look in old .tracepatch_cache/
            legacy = parent / ".tracepatch_cache"
            if legacy.is_dir():
                traces = legacy
            else:
                return []

        entries: list[dict[str, Any]] = []
        for p in sorted(traces.glob("*.json"), reverse=True):
            if len(entries) >= limit:
                break
            try:
                with open(p, encoding="utf-8") as fh:
                    data = json.load(fh)
                entries.append(
                    {
                        "file": str(p),
                        "timestamp": data.get("timestamp"),
                        "label": data.get("label"),
                        "call_count": data.get("call_count", 0),
                        "was_limited": data.get("was_limited", False),
                    }
                )
            except Exception:
                continue
        return entries

    @classmethod
    def load(cls, path: str | Path) -> dict[str, Any]:
        """Load a complete trace log from a JSON file.

        Parameters
        ----------
        path:
            Path to a trace JSON file (as returned by ``trace.logs()``
            or ``t.cache_path``).

        Returns
        -------
        The full JSON contents as a dict.
        """
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
